#!/bin/bash


go=0
  while [ $go ]; do
  
  echo "Enter one of the following actions or press CTRL-D to exit." 
  echo "C - create a new course record"
  echo "R - read an existing course record"
  echo "U - update an existing course record"
  echo "D - delete an existing course record"
  echo "E - update enrolled student count of existing course"
  echo "T - show total course count response"
  
  read -p "Enter a command: " response
  
   if ! [ -z "$response" ]; then
        echo " "
    else
        break
    fi
    
  case "$response" in
    [Cc]) source ./create;;
    [Rr]) source ./read;;
    [Uu]) source ./update;;
    [Dd]) source ./delete;;
    [Ee]) source ./enroll;;
    [Tt]) source ./total;;

 
  
  *) echo "ERROR ENTERED WRONG COMMAND";;
  esac
 
  done
